### PR TITLE
Support os.homedir()

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by phillbaker** [comment]
@staltz looks like the first commit is a dupe of #6. Would you mind doing a new PR against https://github.com/aprock/react-native-os for the other commit? I've been made a maintainer of the NPM package and we'll move development to that fork.

**Comment by staltz** [comment]
Done

**Comment by phillbaker** [comment]
Hi @staltz, I don't have contributor rights on this repo specifically, but I've cherrypicked your commit here: https://github.com/aprock/react-native-os/commit/8dfb18bbaa3abfa0f2d9b96a79636abf45edf473. And published a new version https://www.npmjs.com/package/react-native-os.

**Comment by staltz** [comment]
Given that your repo is being published on npm, I find it sufficient that work continues on that repo. Thanks for cherry-picking. :)

**Pull request closed without merging**
